import Cards from '@/components/cards/cards'
import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Headers from '@/components/header/header'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App !',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Headers />
        <Cards />
        {children}
      </body>
    </html>
  )
}
